spring:
  application:
    name: BLOCKCHAIN_SERVICE

server:
  port: ${BLOCKCHAIN_SERVICE_REST_SERVER_PORT:8080}
  servlet:
    context-path: /blockchain-service

grpc:
  server:
    port: ${BLOCKCHAIN_SERVICE_GRPC_SERVER_PORT:9090}


blockChain:
  difficulty: ${BLOCKCHAIN_DIFFICULTY:4}